# Name: worker_flows.R 
# Purpose: Clean LODES data and calculate worker flows by Census tract
# Last updated: 1/5/2025
# Preliminaries  --------
source("2_code/packages+defaults.R")

# Data: Worker Flows --------

## Tracts --------
DMVW_full_state_tracts = data.frame() %>% as_tibble()
for(i in dir("1_data/LODES/raw_files/", recursive = T, pattern = "*.csv")){
  df = fread(paste0("1_data/LODES/raw_files/",i)) %>% as_tibble %>% 
    mutate(census_year = as.numeric(str_sub(i, start = -8, end = -5))) %>% 
    subset(select = c(w_geocode, h_geocode, S000, census_year))
  DMVW_full_state_tracts = rbind(DMVW_full_state_tracts, df)
  rm(df)
}

## Crosswalks --------
crosswalk = data.frame()
for(i in list.files("1_data/LODES/crosswalks/", pattern = "*_xwalk.csv")){
  crosswalk = rbind(crosswalk, fread(paste0("1_data/LODES/crosswalks/", i)))
}

# Here, I only want to keep the Census tract code ('trct') and the 2020 Census
# Tabulation Block Code ('tabblk2020')
crosswalk = crosswalk %>% subset(select = c(tabblk2020, trct)) %>% 
  as_tibble %>% 
  mutate(tabblk2020 = as.factor(tabblk2020), 
         w_geocode = as.factor(tabblk2020), 
         trct = as.factor(trct))

# Need to align the name of the Census Block Code in the Crosswalk with the one in 
# the actual dataset. 
colnames(crosswalk) = c("h_geocode", "tract", "w_geocode")

# Outflows  --------
# Here, I sum the number of people who live in each tract and go to work anywhere 
# (including in their own home tract). 
outflows_main = DMVW_full_state_tracts %>% subset(select = c(h_geocode, S000)) %>% 
  mutate(h_geocode = as.factor(h_geocode), 
         S000 = as.numeric(S000))

outflows_main = aggregate(S000 ~ h_geocode, data = outflows_main, FUN = sum) %>% 
  left_join(crosswalk) %>% na.omit %>% subset(select = c(h_geocode, tract, S000)) # I'm losing a lot of data here. I think this is because it includes people who live or work outside the DMV, so it doesn't actually matter that much. But there are probably some marginal cases worth checking. 
colnames(outflows_main) = c("geocode", "tract", "outflows")

# Inflows  --------

inflows_main = DMVW_full_state_tracts %>% subset(select = c(w_geocode, S000)) %>% 
  mutate(w_geocode = as.factor(w_geocode), 
         S000 = as.numeric(S000))

inflows_main = aggregate(S000 ~ w_geocode, data = inflows_main, FUN = sum) %>% 
  left_join(crosswalk, by = 'w_geocode') %>% subset(select = c(w_geocode, tract, S000))
colnames(inflows_main) = c("geocode", "tract", "inflows")

# Scale by population --------
# The actual scaling happens in the next chunk, this is just grabbing population data
population <- get_decennial(
  geography = "tract",
  variables = "P1_001N",
  state = str_sub(list.files("1_data/LODES/raw_files/"), start = 1, end = 2) %>% toupper() %>% unique, 
  year = 2020,
  geometry = TRUE
) %>% as_tibble %>% 
  mutate(pop = as.numeric(value), 
         GEOID = as.factor(GEOID)) %>% 
  subset(select = c(GEOID, value))

# All flows  --------

flows = outflows_main %>% left_join(inflows_main) %>% 
  mutate(inflows = ifelse(is.na(inflows), 0, inflows), 
         outflows = ifelse(is.na(outflows), 0, outflows)) %>%
  # Need to aggregate again because was disaggregated by census block before which is too fine 
  aggregate(cbind(inflows, outflows) ~ tract, FUN = sum) %>% 
  mutate(flows = inflows - outflows)
colnames(flows) = c("GEOID", "inflows", "outflows","flows") 
flows = flows %>% left_join(population) %>% 
  mutate(out_scaled = outflows/value, 
         in_scaled = inflows/value, 
         flow_scaled = flows/value, 
         population = value, 
         tract = GEOID) %>% subset(select = -c(value, GEOID))

fwrite(flows, file = paste0(path_out, "cleaned_data/LODES/worker_flows.csv"))

# Cleanup --------
# Removing all objects generated by this file that won't be necessary elsewhere
try(rm(i, population, crosswalk, inflows_main, outflows_main, DMVW_full_state_tracts)) %>% 
  suppressWarnings()

