# Preliminaries --------
source("2_code/packages+defaults.R")
path_in = "3_output/cleaned_data/LODES/"
path_out = "3_output/"

# Creating centroids --------
dmv_tracts <- map_dfr(c("DC", "MD", "VA", "WV"), ~{
  tracts(.x, cb = TRUE, year = 2020)
}, geometry = T) %>%
  st_transform(4326)

dmv_tract_centroids = dmv_tracts %>% st_centroid() # I need to double check that this is the correct way of finding centroids. 

# Calculating distances --------
routing = data.frame()
system.time(
  for(i in 1:length(dmv_tract_centroids$geometry)){
    stats = data.frame()
    for(j in 1:length(stations$station)){
      # stats$station = stations$station[j]
      tryCatch(
        {route = osrmRoute(
          src = st_coordinates(dmv_tract_centroids$geometry[i]), 
          dst = stations[j, 1:2], 
          osrm.profile = "foot"
        )}, error = function(msg){
          return(NA)
        }
      )
      info = cbind(route$duration, route$distance*0.621371, stations$station[j])
      stats = rbind(stats, info) 
      
    }
    colnames(stats) = c("minutes", "miles", "station_name")
    stats$minutes = as.numeric(stats$minutes)
    stats$miles = as.numeric(stats$miles)
    min_dur = min(stats$minutes)
    min_dist = min(stats$miles)
    closest_dur = stats$station_name[which(stats$minutes == min_dur)]
    closest_dist = stats$station_name[which(stats$miles == min_dist)]
    tract = dmv_tract_centroids$GEOID[i]
    info2 = cbind(tract, min_dur, min_dist, closest_dur, closest_dist)
    routing = rbind(routing, info2)
  }
  
)

# Cleanup --------
# Removing all objects generated by this file that won't be necessary elsewhere
