# Preliminaries --------
source("2_code/packages+defaults.R")
source("2_code/function_library/run_all_functions.R")
path_in = "3_output/cleaned_data/LODES/"
path_out = "3_output/"

# Creating centroids --------
# Pulling tracts from all DMV states
dmv_tracts <- map_dfr(c("DC", "MD", "VA", "WV"), ~{
  tracts(.x, cb = TRUE, year = 2020)
}, geometry = T) %>%
  st_transform(4326)

# Getting the CBSA boundary
dc_metro <- core_based_statistical_areas(cb = TRUE, year = 2020) %>%
  filter(str_detect(NAME, "Washington-Arlington-Alexandria, DC-VA-MD-WV")) %>%
  st_transform(4326)
dc_boundary = counties("District of Columbia", cb = T, year = 2020) %>% st_transform(4326)

# Filtering tracts by whether they're within the CBSA
dc_metro_tracts <- dmv_tracts[dc_boundary, ]

# Creating centroids
# I need to double check that this is the correct way of finding centroids. 
dmv_tract_centroids = dc_metro_tracts %>% st_centroid() 

# Calculating distances --------
dmv_distances = map_station_distances(dmv_tract_centroids)
time_elapsed = dmv_distances[2]
dmv_distance = dmv_distances[1] %>% as.data.frame() %>% as_tibble %>% 
  mutate(min_dur = as.numeric(min_dur), 
         min_dist = as.numeric(min_dist))

fwrite(dmv_distance, file = "3_output/cleaned_data/distance_calculations/DC_proper.csv")

# Cleanup --------
# Removing all objects generated by this file that won't be necessary elsewhere
rm(dc_metro, dc_metro_tracts, dmv_tract_centroids, dmv_tracts, dmv_distance, dmv_distances)