# Name: DMV_flows.R 
# Purpose: Create spatial objects for DMV worker flows and plot them in a map. 
# Last updated: 7/4/2025
source("2_code/packages+defaults.R")
path_in = "1_data/LODES/"
path_out = "3_output/"

##################
## DMV Polygons ##
##################

station_poly = update_stations()

dc_flows = fread("3_output/cleaned_data/LODES/worker_flows.csv") %>% 
  rename(GEOID = tract) %>% 
  mutate(GEOID = as.character(GEOID))

dc_metro <- core_based_statistical_areas(cb = TRUE, year = 2020) %>%
  filter(str_detect(NAME, "Washington-Arlington-Alexandria, DC-VA-MD-WV")) %>%
  st_transform(4326)
dc_boundary = counties("District of Columbia", cb = T, year = 2020) %>%
  st_transform(4326)
dc_counties = counties(c("Maryland", "Virginia", "District of Columbia"), cb = T, year = 2020) %>% 
  filter(NAME %in% c("Arlington", "Alexandria", "District of Columbia", "Loudoun",
                     "Prince George's", "Montgomery", "Fairfax", "Falls Church")) %>% 
  filter(!(NAME == "Montgomery" & STUSPS == "VA")) %>%
  st_transform(4326)

dmv_tracts <- map_dfr(c("DC", "MD", "VA", "WV"), ~{
  tracts(.x, cb = TRUE, year = 2020)
}, geometry = T) %>%
  st_transform(4326)

dc_tracts = map_dfr(c("DC"), ~{
  tracts(.x, cb = TRUE, year = 2020)
}) %>%
  st_transform(4326)  %>% erase_water() %>% 
  left_join(dc_flows)

dc_metro_tracts <- dmv_tracts[dc_counties, ] %>% 
  erase_water() %>% 
  left_join(dc_flows)
ggplot() + 
  # geom_sf(data = dc_metro_tracts, fill = "white", color = "black") +
  # geom_sf(data = dc_counties, fill = NA, color = "black") +
  geom_sf(data = dc_metro_tracts, color = "blue", aes(fill = outflows)) +
  geom_sf(data = dc_metro_tracts %>% filter(AFFGEOID == "1400000US51059980200"), color = "red", fill ="red") + 
  geom_sf(data = station_poly %>% filter(grepl(pattern = "Green", x = lines_serviced)), size = 3, shape = 23, fill = "green") +
  geom_sf(data = station_poly %>% filter(grepl(pattern = "Red", x = lines_serviced)), size = 3, shape = 23, fill = "red") +
  geom_sf(data = station_poly %>% filter(grepl(pattern = "Silver", x = lines_serviced)), size = 3, shape = 23, fill = "gray") +
  geom_sf(data = station_poly %>% filter(grepl(pattern = "Blue", x = lines_serviced)), size = 3, shape = 23, fill = "blue") +
  geom_sf(data = station_poly %>% filter(grepl(pattern = "Yellow", x = lines_serviced)), size = 3, shape = 23, fill = "yellow") +
  geom_sf(data = station_poly %>% filter(grepl(pattern = "Orange", x = lines_serviced)), size = 3, shape = 23, fill = "orange") +
  # geom_sf(data = dmv_tract_centroids, size = 1, shape = 15, fill = "red") + 
  geom_sf(data = dc_boundary, color = "yellow", fill = NA, size = 10) + 
  theme_classic() + 
  # Entire metro view
  # coord_sf(default_crs = sf::st_crs(4326),
  #          xlim = c(-77.25, -76.8),
  #          ylim = c(38.75, 39.15)
  # )
  # DC view
  coord_sf(default_crs = sf::st_crs(4326),
           xlim = c(-77.29, -76.83),
           ylim = c(38.75, 39.1)
  ) + 
  guides(fill=guide_legend(title="Number of Workers")) + 
  theme(legend.position="bottom")

ggsave(filename = "3_output/dmv_map.png")

# Cleanup --------
# Removing all objects generated by this file that won't be necessary elsewhere
try(rm(dc_boundary, dc_counties, dc_flows, dc_metro, dc_metro_tracts, dc_tracts, dmv_tracts, station_poly, i)) %>%
suppressWarnings()
